name: CI

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Spotless Check
        uses: ./.github/actions/gradle-action
        with:
          command: spotlessCheck

  check:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Build & Test
        uses: ./.github/actions/gradle-action
        with:
          command: check
