name: on-pull-request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Spotless Check
        uses: ./.github/actions/gradle-action
        with:
          command: spotlessCheck

  check:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Build & Test
        uses: ./.github/actions/gradle-action
        with:
          command: check -x spotlessCheck

  package-macos:
    needs: check
    runs-on: macos-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Package DMG (unsigned)
        uses: ./.github/actions/gradle-action
        with:
          command: packageDmg

  package-windows:
    needs: check
    runs-on: windows-latest
    timeout-minutes: 20

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Package MSI (unsigned)
        uses: ./.github/actions/gradle-action
        with:
          command: packageMsi
