name: on-pull-request

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Typecheck
        uses: ./.github/actions/pnpm-action
        with:
          command: typecheck

  check:
    needs: lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Build & Test
        uses: ./.github/actions/pnpm-action
        with:
          command: test
