name: seed-pnpm-cache

on:
  push:
    branches: [main]

jobs:
  seed-cache:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: ./.github/actions/setup-node-pnpm

      - name: Build
        run: pnpm build
